# Generated by Django 5.2.8 on 2026-03-14 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Med',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(db_column='name', max_length=30)),
                ('surname', models.CharField(db_column='surname', max_length=30)),
                ('description', models.CharField(db_column='description', max_length=200)),
                ('email', models.CharField(db_column='email', max_length=30)),
                ('telephone', models.CharField(db_column='telephone', max_length=30)),
                ('level_spec', models.IntegerField(db_column='level_spec', default=1)),
                ('image', models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images')),
                ('is_verified', models.BooleanField(default=False)),
                ('vacation_days_total', models.PositiveSmallIntegerField(default=20)),
                ('vacation_days_remaining', models.PositiveSmallIntegerField(default=20)),
                ('vacation_days_year', models.PositiveSmallIntegerField(default=2026)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='med', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField(db_column='start_date')),
                ('endDate', models.DateField(db_column='end_date')),
                ('status', models.IntegerField(db_column='status', default=0)),
                ('idMed', models.ForeignKey(db_column='id_med', on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='meds.med')),
            ],
        ),
        migrations.CreateModel(
            name='SpecializationUpgradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_level', models.PositiveSmallIntegerField()),
                ('status', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.CharField(blank=True, default='', max_length=255)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_requests', to='meds.med')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 0)), fields=('med',), name='unique_pending_spec_request_per_med')],
            },
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='date')),
                ('startTime', models.TimeField(db_column='start_time')),
                ('endTime', models.TimeField(db_column='end_time')),
                ('breakTime', models.TimeField(db_column='break_time', default='12:00')),
                ('idMed', models.ForeignKey(db_column='id_med', on_delete=django.db.models.deletion.CASCADE, related_name='work_times', to='meds.med')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('idMed', 'date'), name='unique_override_per_date_and_med')],
            },
        ),
    ]
