# Generated by Django 5.2.8 on 2026-03-14 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meds', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllInterventions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(db_column='description')),
                ('duration', models.IntegerField(db_column='duration')),
                ('price', models.DecimalField(db_column='price', decimal_places=2, default=0.0, max_digits=8)),
                ('level', models.IntegerField(db_column='level', default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('star', models.IntegerField(db_column='star')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idMed', models.ForeignKey(db_column='id_med', on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='meds.med')),
                ('idPat', models.ForeignKey(db_column='id_pat', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='patients.pat')),
            ],
        ),
    ]
