# Generated by Django 5.2.8 on 2026-03-14 16:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=30)),
                ('surname', models.CharField(db_column='surname', max_length=30)),
                ('description', models.CharField(db_column='description', max_length=200)),
                ('secretNotes', models.CharField(db_column='secretNotes', max_length=200)),
                ('email', models.CharField(db_column='email', max_length=30)),
                ('telephone', models.CharField(db_column='telephone', max_length=30)),
                ('image', models.ImageField(blank=True, default='images/defaultP.jpg', null=True, upload_to='images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pat_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(db_column='description')),
                ('duration', models.IntegerField(db_column='duration')),
                ('status', models.CharField(db_column='status', default='Zakazan', max_length=50)),
                ('date', models.DateField(db_column='date', default=django.utils.timezone.now)),
                ('time', models.TimeField(db_column='time', default=django.utils.timezone.now)),
                ('idMed', models.ForeignKey(db_column='id_med', on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='meds.med')),
                ('idPat', models.ForeignKey(db_column='id_pat', on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='patients.pat')),
            ],
        ),
    ]
